name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build steamcmd
      env:
        STEAM_USER: anonymous
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u adamveld12 -p ${DOCKER_PASSWORD}
        TAG=$(git rev-parse --short=6 HEAD)
        docker build -t gamenight/steamcmd:${TAG} ./steamcmd
        docker tag gamenight/steamcmd:${TAG} gamenight/steamcmd:latest
        docker push -a gamenight/steamcmd
