name: Docker Image CI

on:
  schedule:
    - cron:  '0 14 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  steamcmd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build steamcmd
      env:
        STEAM_USER: anonymous
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        source ./build.sh
        build steamcmd ${SHA}

  dontstarve:
    runs-on: ubuntu-latest
    needs: [steamcmd]
    steps:
    - uses: actions/checkout@v2
    - name: Build dontstarve
      env:
        STEAM_USER: anonymous
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        source ./build.sh
        build dontstarve ${SHA}

  valheim:
    runs-on: ubuntu-latest
    needs: [steamcmd]
    steps:
    - uses: actions/checkout@v2
    - name: Build valheim
      env:
        STEAM_USER: anonymous
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        source ./build.sh
        build valheim ${SHA}

  minecraft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build minecraft
      env:
        STEAM_USER: anonymous
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        source ./build.sh
        build minecraft 1.17

  terraria:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build terraria
      env:
        STEAM_USER: anonymous
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        source ./build.sh
        build terraria 1423

  factorio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build factorio
      env:
        STEAM_USER: anonymous
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        source ./build.sh
        build factorio stable
        build factorio ${SHA}
