name: Games Image Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  minecraft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build minecraft
        env:
          STEAM_USER: anonymous
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          .hack/build.sh minecraft 1.18.1

  terraria:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build terraria
        env:
          STEAM_USER: anonymous
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          .hack/build.sh terraria 1423

  factorio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build factorio
        env:
          STEAM_USER: anonymous
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          .hack/build.sh factorio 1.1.50

  dwarf_fortress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build dwarf fortress
        env:
          STEAM_USER: anonymous
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          .hack/build.sh dwarf_fortress 47_05
