name: Master Build and Publish Release

on:
  push:
    branches: [master]
    paths:
      - "versions.txt"
jobs:
  steamcmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build SteamCMD
        uses: docker/build-push-action@v3
        env:
          STEAM_USER: anonymous
        with:
          context: ./steamcmd
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/gamenight/steamcmd:latest
            docker.io/gamenight/steamcmd:${{ github.sha }}
            ghcr.io/${{ github.repository }}/steamcmd:latest
            ghcr.io/${{ github.repository }}/steamcmd:${{ github.sha }}

  build-game-servers:
    runs-on: ubuntu-latest
    needs: [steamcmd]
    strategy:
      matrix:
        game:
          - "minecraft"
          - "terraria"
          - "factorio"
          - "dwarf_fortress"
          - "valheim"
          - "satisfactory"
          # - "rust"
          # - "dontstarve"
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{matrix.game}}
        uses: docker/build-push-action@v3
        env:
          STEAM_USER: anonymous
        with:
          context: ./${{ matrix.game }}
          platforms: linux/amd64
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/adamveld12/gamenight.git
            org.opencontainers.image.url=https://github.com/adamveld12/gamenight
            org.opencontainers.image.revision=${{ github.sha }}
            org.gamenight.game-id=${{ matrix.game }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.authors=Adam Veldhousen <adam@vdhsn.com>
          tags: |
            docker.io/gamenight/${{ matrix.game }}:latest
            docker.io/gamenight/${{ matrix.game }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ matrix.game }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.game }}:${{ github.sha }}
