name: PR Build WIP

on:
  pull_request:
    branches: [master, trunk]

jobs:
  steamcmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build SteamCMD
        env:
          STEAM_USER: anonymous
        run: |
          .hack/build.sh steamcmd WIP
  build-game-servers:
    runs-on: ubuntu-latest
    needs: [steamcmd]
    strategy:
      matrix:
        game:
          - "minecraft"
          - "terraria"
          - "factorio"
          - "dwarf_fortress"
          - "valheim"
          - "satisfactory"
          # - "rust"
          # - "dontstarve"
    steps:
      - uses: actions/checkout@v2
      - name: Check for image changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - ${{ matrix.game }}/**
      - if: steps.changes.outputs.src == 'true'
        name: Build ${{ matrix.game }}
        env:
          STEAM_USER: anonymous
        run: |
          .hack/build.sh ${{ matrix.game }} WIP
