name: PR Build WIP

on:
  pull_request:
    branches: [master, trunk]

jobs:
  build-non-steam:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game:
          - "minecraft"
          - "terraria"
          - "factorio"
          - "dwarf_fortress"
    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.game }}
        env:
          STEAM_USER: anonymous
        run: |
          .hack/build.sh ${{ matrix.game }} WIP
  steamcmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build SteamCMD
        env:
          STEAM_USER: anonymous
        run: |
          .hack/build.sh steamcmd WIP
  build-steam:
    runs-on: ubuntu-latest
    needs: [steamcmd]
    strategy:
      matrix:
        game:
          - "valheim"
          - "rust"
          - "dontstarve"
    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.game }}
        env:
          STEAM_USER: anonymous
        run: |
          .hack/build.sh ${{ matrix.game }} WIP
